# Site settings
title: Modern Blog
description: Modern-Blog A Elegant template for Jekyll
keywords: Modern, Blogging, Fun
author: Wferr
baseurl: "blog" # the subpath of your site, e.g. /blog/
url: "https://iseexuhs.github.io" # the base hostname & protocol for your site
