# Site settings
title: ISEE-micro
description: 致力于传播声波器件、柔性电子器件的最新研究进展
keywords: Modern, Blogging, Fun
author: H.S. Xu
baseurl: "research" # the subpath of your site, e.g. /blog/
url: "https://iseex.github.io" # the base hostname & protocol for your site
